title: "Ayush Raj"
description: "CS Undergrad | Prompt Engineering | AI Automation | Python | REST APIs"

email: "ayushraj4207@gmail.com"
phone: "+91 7541884619"
location: "Ghaziabad, India"

github_username: "ayushraj2311"
linkedin_username: "ayush-raj-a2b28321b"

avatar: "ayush.jpg" # Upload your profile image and rename it to this

content:
  - title: About Me
    layout: text
    content: |
      I'm a Computer Science undergraduate passionate about AI-driven automation, prompt engineering, and unstructured data extraction. I've built LLM-powered tools, automated data pipelines, and contributed to real-world projects using Python, FastAPI, and MongoDB. I'm eager to solve impactful problems and contribute to teams building scalable tech.

  - title: Education
    layout: list
    content:
      - title: KIET Group of Institutions
        sub_title: B.Tech in Computer Science & IT
        caption: 2022 – 2026 | GPA: 7.8/10
        description: |
          Relevant Courses: Data Structures, Operating Systems, DBMS, CN, SE.

      - title: Kendriya Vidyalaya No. 2, Patna
        sub_title: Intermediate & High School
        caption: 2019 – 2021
        description: |
          Intermediate (2021): 84%  
          High School (2019): 89%

  - title: Projects
    layout: list
    content:
      - title: LLM-Based Document Extractor
        sub_title: Python, OpenAI API, FastAPI, MongoDB
        description: |
          Extracts structured data from contracts, invoices, and IDs using few-shot prompting. Scales manual form tasks with 95% automation.

      - title: Client Data Intake Pipeline
        sub_title: Python, FastAPI, MongoDB
        description: |
          Automates PDF field extraction and validation. Integrated with REST APIs, includes error handling and automated tests.

  - title: Experience
    layout: list
    content:
      - title: GoPro Media (Remote)
        sub_title: Frontend Developer Intern
        caption: May 2025 – June 2025
        description: |
          Developed React UI components, integrated backend APIs, and improved page load by 30%. Worked in CI/CD and Agile sprints.

  - title: Skills
    layout: list
    content:
      - title: Programming
        description: |
          Python, C++, Bash, JavaScript
      - title: Tools & Frameworks
        description: |
          FastAPI, Git, Postman, Wireshark, PlatformIO
      - title: AI & Automation
        description: |
          Prompt Engineering, OpenAI API, JSON, LLM Templates
      - title: Databases & APIs
        description: |
          MongoDB, Firebase, NoSQL, REST APIs
      - title: Concepts
        description: |
          Data Pipelines, Deployment, Troubleshooting, Technical Docs

  - title: Certifications
    layout: list
    content:
      - title: Prompt Engineering for Developers
        sub_title: DeepLearning.AI
      - title: Networking Basics • Python Essentials • AWS Cloud
        sub_title: Cisco, Infosys, LinkedIn

  - title: Achievements
    layout: list
    content:
      - title: SIH Hackathon Finalist
        description: |
          Built a mental health app using NLP & AI.
      - title: Bihar State Basketball Player
        description: |
          Represented Bihar at the National U23 Championship.
      - title: 200+ DSA Problems
        description: |
          Solved on LeetCode and Codeforces.

  - title: Leadership & Community
    layout: list
    content:
      - title: Dev Cell & NGO Campaigns
        description: |
          Led events and awareness drives on campus.
      - title: Campus Trainer
        description: |
          Conducted workshops on Prompt Engineering and Firebase.
